version: '3.8'
services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: blogify_db
    ports:
      - "3306:3306"
    volumes:
      - blogify_mysql:/var/lib/mysql

  redis:
    image: redis:7-alpine
    ports:
      - "6381:6379"
    container_name: blogify-redis

volumes:
  blogify_mysql:
